"""sync chatbots models after env fix

Revision ID: acec4b03af03
Revises: 000000000010
Create Date: 2025-09-04 13:45:00.992731

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'acec4b03af03'
down_revision = '000000000010'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_agent_tenant_id'), 'agent', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_agent_network_tenant_id'), 'agent_network', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_agent_network_run_run_id'), 'agent_network_run', ['run_id'], unique=False)
    op.alter_column('chat_message', 'tenant_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.drop_index(op.f('ix_chat_message_tenant'), table_name='chat_message')
    op.drop_index(op.f('ix_chat_message_thread_created'), table_name='chat_message')
    op.create_index(op.f('ix_chat_message_tenant_id'), 'chat_message', ['tenant_id'], unique=False)
    op.create_index('ix_message_thread_created', 'chat_message', ['thread_id', 'created_at'], unique=False)
    op.alter_column('chat_thread', 'tenant_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.drop_index(op.f('ix_chat_thread_chatbot_user'), table_name='chat_thread')
    op.drop_index(op.f('ix_chat_thread_last_message_at'), table_name='chat_thread')
    op.drop_index(op.f('ix_chat_thread_status'), table_name='chat_thread')
    op.drop_index(op.f('ix_chat_thread_tenant'), table_name='chat_thread')
    op.create_index(op.f('ix_chat_thread_tenant_id'), 'chat_thread', ['tenant_id'], unique=False)
    op.create_index('ix_thread_chatbot_user', 'chat_thread', ['chatbot_id', 'user_id'], unique=False)
    op.create_index('ix_thread_last_message_at', 'chat_thread', ['last_message_at'], unique=False)
    op.create_index('ix_thread_status', 'chat_thread', ['status'], unique=False)
    op.create_index(op.f('ix_chatbot_tenant_id'), 'chatbot', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chatbot_tenant_id'), table_name='chatbot')
    op.drop_index('ix_thread_status', table_name='chat_thread')
    op.drop_index('ix_thread_last_message_at', table_name='chat_thread')
    op.drop_index('ix_thread_chatbot_user', table_name='chat_thread')
    op.drop_index(op.f('ix_chat_thread_tenant_id'), table_name='chat_thread')
    op.create_index(op.f('ix_chat_thread_tenant'), 'chat_thread', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_chat_thread_status'), 'chat_thread', ['status'], unique=False)
    op.create_index(op.f('ix_chat_thread_last_message_at'), 'chat_thread', ['last_message_at'], unique=False)
    op.create_index(op.f('ix_chat_thread_chatbot_user'), 'chat_thread', ['chatbot_id', 'user_id'], unique=False)
    op.alter_column('chat_thread', 'tenant_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.drop_index('ix_message_thread_created', table_name='chat_message')
    op.drop_index(op.f('ix_chat_message_tenant_id'), table_name='chat_message')
    op.create_index(op.f('ix_chat_message_thread_created'), 'chat_message', ['thread_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_chat_message_tenant'), 'chat_message', ['tenant_id'], unique=False)
    op.alter_column('chat_message', 'tenant_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.drop_index(op.f('ix_agent_network_run_run_id'), table_name='agent_network_run')
    op.drop_index(op.f('ix_agent_network_tenant_id'), table_name='agent_network')
    op.drop_index(op.f('ix_agent_tenant_id'), table_name='agent')
    # ### end Alembic commands ###


