"""init datasources

Revision ID: f9c0cc3f5321
Revises: 
Create Date: 2025-08-13 12:16:20.008415

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f9c0cc3f5321'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_source',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('updated_by', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_data_source_tenant_name')
    )
    op.create_index('ix_data_source_tenant_enabled', 'data_source', ['tenant_id', 'is_enabled'], unique=False)
    op.create_index(op.f('ix_data_source_tenant_id'), 'data_source', ['tenant_id'], unique=False)
    op.create_index('ix_data_source_tenant_type', 'data_source', ['tenant_id', 'type'], unique=False)
    op.create_table('data_source_config',
    sa.Column('data_source_id', sa.String(length=36), nullable=False),
    sa.Column('config_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('config_schema_version', sa.String(length=32), nullable=True),
    sa.Column('redaction_map', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_source.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('data_source_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_source_config')
    op.drop_index('ix_data_source_tenant_type', table_name='data_source')
    op.drop_index(op.f('ix_data_source_tenant_id'), table_name='data_source')
    op.drop_index('ix_data_source_tenant_enabled', table_name='data_source')
    op.drop_table('data_source')
    # ### end Alembic commands ###


